config/routes.rb
Rails.application.routes.draw do
  
  resources :reports
  resources :events
  get 'map/index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :users
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin_user', as: 'rails_admin'
  
  resources :pictures do
    resources :comments
  end

  resources :events do
    resources :comments
  end
  
  resources :pictures
  resources :locs
  resources :arts
  resources :pictures do
     resources :assets
   end

  root :to => 'events#root'
  
  get '/about', to: 'pages#about'
  get '/blog', to: 'arts#index'
  get '/picture', to: 'pictures#index'
  get '/me', to: 'pages#me'
  get '/event', to: 'events#index'
  get 'events/:id/picture/:name' => 'events#show_picture',
       as: 'events_picture'
  get 'events_by/:id' => 'events#index_by_user', as: 'events_by'
  get 'events_pasts'  => 'events#pasts', as: 'events_pasts'
  get 'events/:id/dup' => 'events#duplicate', as: 'dup_event'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :comments, :allow_destroy => true
  belongs_to :user
  validates :title, presence: true
  validates :opendate, presence: true
  validates :address_title, presence: true
  #validates :picture_main, presence: true

  def opendate_short
    if opendate.year == Date.today.year
      d = opendate.strftime("%m/%d")
    else
      d = opendate.strftime("%Y/%m/%d")
    end
    w = %w(日 月 火 水 木 金 土)[opendate.wday]
    d+" ("+w+") "+(opendate_memo == nil ? "" : opendate_memo)
  end

  def limit_short
    return "なし" if limit == nil || limit == 0
    return "#{limit} 名"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :show_picture, :duplicate]
  before_action :authenticate_user!, except: [:root, :pasts, :show, :show_picture, :index_by_user]

  respond_to :html

  def root
    @events = Event.where("opendate >= ? AND visible = true",Date.today.to_s).order("opendate").limit(12)
    respond_with(@events)
  end

  def index
    # Use for user home
    @upcomings = Event.where("opendate >= ? AND user_id = ? AND visible = true",Date.today.to_s,current_user.id).order("opendate ASC")
    @ends = Event.where("opendate < ? AND user_id = ? AND visible = true",Date.today.to_s,current_user.id).order("opendate DESC")
    respond_with(@upcomings,@ends)
  end

  def index_by_user
    @user = User.find(params[:id])
    raise ActionController::RoutingError.new('User not found.') unless @user
    @upcomings = Event.where("opendate >= ? AND user_id = ? AND visible = true",Date.today.to_s,@user.id).order("opendate ASC")
    @ends = Event.where("opendate < ? AND user_id = ? AND visible = true",Date.today.to_s,@user.id).order("opendate DESC")
  end

  def pasts
    @ends = Event.where("opendate < ? AND visible = true",Date.today.to_s).order("opendate DESC")
    respond_with(@ends)
  end

  def show
    respond_with(@event)
    @comment = Event.find(params[:id]).comments.build
  end

  def new
    @event = Event.new
    @event.user_id = current_user.id
    respond_with(@event)
  end

  def edit
    if current_user.id != @event.user_id
      raise ActionController::RoutingError.new('This event is not yours.')
    end
  end

  def duplicate
    if current_user.id != @event.user_id
      raise ActionController::RoutingError.new('This event is not yours.')
    end
    #@event.id = nil
    @event.visible = true # Always invisible after duplication.
  end

  def create
    @event = Event.new(event_params)
    if params[:event][:id]
      # from duplicate
      orig = Event.find(params[:event][:id])
      @event.picture_main = orig.picture_main
      @event.picture_1 = orig.picture_1
      @event.picture_2 = orig.picture_2
      @event.picture_3 = orig.picture_3
    end
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  def show_picture
    n = "picture_"+ (params["name"] || "main")
    d = @event.send(n)
    if d
      send_data d, :type => 'image/jpeg', :disposition => "inline"
    else
      raise ActionController::RoutingError.new('Picture of '+@event.title+' '+n+' not found')
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def adjust_image(b)
      require 'RMagick'
      i = Magick::Image.from_blob(b.read)[0]
      if i.columns > 1024
        return i.resize(0.5).to_blob
      else
        return i.to_blob
      end
    end

    def event_params
      p = params.require(:event).permit(:user_id, :title, :opendate, :opendate_memo, :address_title, :address, :postal, :address_embed, :fee, :fee_memo, :limit, :desc_short, :desc_long, :picture_main, :picture_1, :picture_2, :picture_3, :url, :url_facebook, :url_twitter, :visible,
        :commenter, :body, comments_attributes: [:commenter, :body])
      [:picture_main,:picture_1,:picture_2,:picture_3].each do |k|
        p[k] = adjust_image(p[k]) if p[k]
      end
      return p
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-md-4">
  <div class="event">
    <h3><%= link_to event.title, event %></h3>
    <p>
      <span class="glyphicon glyphicon-time" title="開催日"></span> <%= event.opendate_short %><br/>
      <span class="glyphicon glyphicon-map-marker" title="場所"></span> <%= event.address_title %><br/>
      <span class="glyphicon glyphicon-user" title="主催者"></span> <%= link_to event.user.name,events_by_path(event.user) %>
    </p>
    <%= image_tag events_picture_path(event.id,"main") %>
  </div>
</div>

app/views/events/_form.html.erb
<% f = @f %>
  <% if @event.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
      <p><%= pluralize(@event.errors.count, "error") %>個のエラー:</p>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :タイトル %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :開催日 %>
    <%= f.date_field :opendate, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :開催日のメモ %>
    <%= f.text_field :opendate_memo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :開催場所 %>
    <%= f.text_field :address_title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :住所 %>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :郵便番号 %>
    <%= f.text_field :postal, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :地図URL %>
    <%= f.text_field :address_embed, class: "form-control" %>
    <small>サイズ、形式？</small>
  </div>
  <div class="form-group">
    <%= f.label :参加費 %>
    <%= f.number_field :fee, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :参加費メモ %>
    <%= f.text_field :fee_memo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :収容人数 %>
    <%= f.number_field :limit, class: "form-control" %>
    <small>定員なしの場合、0に設定してください。</small>
  </div>
  <div class="form-group">
    <%= f.label :概要 %>
    <%= f.text_area :desc_short, class: "form-control" %>
    <small>80文字程度推奨。 <span id="n_desc_short">0</span></small>
    <script>
      $("#event_desc_short").keyup(function(e){
        $("#n_desc_short").text($(e.target).val().length);
      });
      $("#n_desc_short").text($(e.target).val().length);
    </script>
  </div>
  <div class="form-group">
    <%= f.label :詳細 %>
    <%= f.text_area :desc_long, rows: 10, class: "form-control" %>
    <small>500~1000文字程度推奨。 <span id="n_desc_long">0</span></small>
    <script>
      $("#event_desc_long").keyup(function(e){
        $("#n_desc_long").text($(e.target).val().length);
      });
      $("#n_desc_long").text($(e.target).val().length);
    </script>
  </div>
  <div class="form-group">
    <%= f.label :メイン写真 %>
    <%= f.file_field :picture_main, class: "form-control" %>
    <small>幅600px程度</small>
  </div>
  <div class="form-group">
    <%= f.label :写真１ %>
    <%= f.file_field :picture_1, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :写真２ %>
    <%= f.file_field :picture_2, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :写真３ %>
    <%= f.file_field :picture_3, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :URL %>
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Facebook %>
    <%= f.text_field :url_facebook, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Twitter %>
    <%= f.text_field :url_twitter, class: "form-control" %>
  </div>
  <div class="checkbox">
    <label>
      <%= f.check_box :visible %>公開する
    </label>
  </div>
  <div class="form-group">
    <%= f.label :user_id, "主催者" %>
    <%= @event.user.name %>
    <%= f.hidden_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit nil,class: "btn btn-primary" %>
  </div>

app/views/events/_index_event.html.erb
<table class="table">
  <thead>
    <tr>
      <th>開催日</th>
      <th>場所</th>
      <th>タイトル</th>
      <th>参加費</th>
      <th>定員</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% events.each do |event| %>
      <% if event.visible %>
      <tr>
      <% else %>
      <tr style="background-color: #eee;">
      <% end %>
      <td><%= event.opendate_short %></td>
      <td><%= event.address_title %></td>
      <td><%= event.title %></td>
      <td><%= event.fee %></td>
      <td><%= event.limit %><%= event.visible %></td>
      <td><%= link_to '閲覧', event, class: "btn btn-default" %>
      <%= link_to '編集', edit_event_path(event), class: "btn btn-default" %>
      <%= link_to '削除', event, method: :delete, data: { confirm: 'よろしいですか?' }, class: "btn btn-danger" %>
      <%= link_to '複製', dup_event_path(event), class: "btn btn-default" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/events/duplicate.html.erb
<h1>複製</h1>
<div class="row">
  <div class="col-md-6">
    <%= form_for(@event, url: events_path, method: :post) do |f| %>
    <%= f.hidden_field :id %>
    <% @f = f %>
    <%= render 'form' %>
    <% end %>
  </div>
</div>
<hr/>
<div class="row">
  <div class="col-md-6">
    <%= link_to '一覧に戻る', events_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/events/edit.html.erb
<h1>編集</h1>
<div class="row">
  <div class="col-md-6">
    <%= form_for(@event) do |f| %>
    <% @f = f %>
    <%= render 'form' %>
    <% end %>
  </div>
</div>
<hr/>
<div class="row">
  <div class="col-md-6">
<%= link_to '閲覧', @event, class: 'btn btn-default' %>
<%= link_to '一覧に戻る', events_path, class: 'btn btn-default' %>

  </div>
</div>

app/views/events/index.html.erb
<h3>国東半島"来ちょくれ倶楽部"のイベント告知サイトです。</h3>
<h5></h5>

<br><br><br><br>
<p>
  <%= link_to '新しいイベントを登録する', new_event_path, class: "btn btn-default" %>
 <%= link_to 'ユーザ情報を変更する', edit_user_registration_path, class: "btn btn-default" %>
</p>
<h3>近日開催</h3>
<%= render partial: "index_event", locals: {events: @upcomings} %>

<h3>開催済み</h3>
<%= render partial: "index_event", locals: {events: @ends} %>

app/views/events/index_by_user.html.erb
<h1><%= @user.name %> 主催のイベント</h1>
<h3>近日開催</h3>
<div class="row">
  <% @upcomings.each do |event| %>
    <%= render partial: 'event', locals: {event: event} %>
  <% end %>
</div>
<h3>開催済み</h3>
<div class="row">
  <% @ends.each do |event| %>
    <%= render partial: 'event', locals: {event: event} %>
    <% end %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/pasts.html.erb
<div class="row">
  <div class="col-md-6">
    <h2>開催済み</h2>
  </div>
  <div class="col-md-6 text-right">
    <%= link_to 'トップページ', root_path, class: 'btn btn-default' %>
  </div>
</div>
<div class="row">
    <% @ends.each do |event| %>
      <%= render partial: 'event', locals: {event: event} %>
    <% end %>
</div>
<div class="row">
  <div class="col-md-12 text-right">
    <%= link_to 'トップページ', root_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/events/root.html.erb
<div class="row">
  <% if @events.empty? %>
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-body text-center">
          開催予定のイベントはありません。
        </div>
      </div>
    </div>
  <% else %>
    <% @events.each do |event| %>
      <%= render partial: 'event', locals: {event: event} %>
    <% end %>
  <% end %>
</div>
<div class="row">
  <div class="col-md-12 text-right">
    <%= link_to '開催済み', events_pasts_path, class: 'btn btn-default' %>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <h2>このサイトについて</h2>
    <p>「LM Events」では、シンプルなイベント告知ページを作ることができます。</p>
    <p>SNS等でのイベント告知のランディングページとしての利用を想定しています。
      目的・ジャンルを問わず、様々なタイプのイベントの告知にお使い頂けます。
      細かい規約は設けていませんが、良識のある利用をお願い致します（不適切と判断した投稿は予告なく削除することがあります）。</p>
  </div>
<div class="col-md-6">
  <h2>このアプリについて</h2>
  <p>Ruby on Railsの勉強会で作った習作をそのまま配備しています。
    ソースコードは<a href="https://github.com/yosei/events.lmlab.net">GitHubで公開</a>していますので、
    自由にフォークして独自のサイト作りに役立てて頂いても構いません。機能追加のリクエストや不具合報告も歓迎します。</p>
</div>
</div>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<div class="row event-detail">
  <div class="col-md-6">
    <p><%= @event.desc_short.gsub("\n","<br/>").html_safe %></p>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= @event.desc_long.gsub("\n","<br/>").html_safe %>
      </div>
    </div>
    <table class="table">
      <tr>
        <th><span class="glyphicon glyphicon-time"></span> 日時</th>
        <td><%= @event.opendate_short %></td>
      </tr>
      <tr>
        <th><span class="glyphicon glyphicon-map-marker"></span> 場所</th>
        <td><%= @event.address_title %><br/>
        <small><%= @event.postal %> <%= @event.address %></small>
        </td>
      </tr>
      <tr>
        <th style="white-space: nowrap"><span class="glyphicon glyphicon-user"></span> 主催者</th>
        <td><%= link_to @event.user.name, events_by_path(@event.user.id) %></td>
      </tr>
      <tr>
        <th><span class="glyphicon glyphicon-yen"></span> 参加費</th>
        <td><%= @event.fee %>円<br/><small><%= @event.fee_memo %></small></td>
      </tr>
      <tr>
        <th><span class="glyphicon glyphicon-plus"></span> 定員</th>
        <td><%= @event.limit_short %></td>
      </tr>
      <tr>
        <th>URL</th>
        <td>
          <%= (link_to @event.url) if @event.url %><br/>
          <%
          f = image_tag '/images/facebook.png', class: "icon"
          t = image_tag '/images/twitter.png', class: "icon"
          %>
          <%= link_to f, @event.url_facebook if @event.url_facebook.present? %>
          <%= link_to t, @event.url_twitter if @event.url_twitter.present? %>
        </td>
      </tr>
    </table>
  </div>
  <div class="col-md-6">
    <%= image_tag events_picture_path(@event.id,"main"), class: "img-rounded" %>
    <br/><br/>
    <div class="row">
      <div class="col-md-4">
        <%= (link_to (image_tag events_picture_path(@event.id,"1"), class: "img-rounded"), events_picture_path(@event.id,"1")) if @event.picture_1 %>
      </div>
      <div class="col-md-4">
        <%= (link_to (image_tag events_picture_path(@event.id,"2"), class: "img-rounded"), events_picture_path(@event.id,"2")) if @event.picture_2 %>
      </div>
      <div class="col-md-4">
        <%= (link_to (image_tag events_picture_path(@event.id,"3"), class: "img-rounded"), events_picture_path(@event.id,"3")) if @event.picture_3 %>
      </div>
    </div>
  </div>
</div>
<hr/>
<%= render "comments/form" %>

<% if user_signed_in? && current_user.id == @event.user_id %>
<div class="row">
  <div class="col-md-12">
    <%= link_to '編集', edit_event_path(@event), class: "btn btn-default" %>
    <%= link_to '一覧に戻る', events_path, class: "btn btn-default" %>
  </div>
</div>
<% end %>