config/routes.rb
Rails.application.routes.draw do
  
  resources :reports
  resources :events
  get 'map/index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :users
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin_user', as: 'rails_admin'
  
  resources :pictures do
    resources :comments
  end

  resources :events do
    resources :comments
  end
  
  resources :pictures
  resources :locs
  resources :arts
  resources :pictures do
     resources :assets
   end

  root :to => 'events#root'
  
  get '/about', to: 'pages#about'
  get '/blog', to: 'arts#index'
  get '/picture', to: 'pictures#index'
  get '/me', to: 'pages#me'
  get '/event', to: 'events#index'
  get 'events/:id/picture/:name' => 'events#show_picture',
       as: 'events_picture'
  get 'events_by/:id' => 'events#index_by_user', as: 'events_by'
  get 'events_pasts'  => 'events#pasts', as: 'events_pasts'
  get 'events/:id/dup' => 'events#duplicate', as: 'dup_event'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :comments, :allow_destroy => true
  has_many :assets, :dependent => :destroy
  accepts_nested_attributes_for :assets, :allow_destroy => true
   # ファイルの拡張子を指定（これがないとエラーが発生する）
  geocoded_by :address
  after_validation :geocode
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @comment = Picture.find(params[:id]).comments.build
    @pictures = Picture.all
    @hash = Gmaps4rails.build_markers(@pictures) do |picture, marker|
      marker.lat picture.latitude
      marker.lng picture.longitude
    end
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
    3.times { @picture.assets.build }
  end

  # GET /pictures/1/edit
  def edit
    @picture.assets.build
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:name, :photo, :content, :title, :address, :latitude, :longitude,
                                      :access, :worktime, :rest, :fee, :credit, :parking, :parkingnumber,
                                      :parkingfee, :phonenumber, :image, :commneter, :body,
                                      assets_attributes: [:image,], comments_attributes: [:commenter, :body])
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_address.html.erb
<p><h4>【基本情報】<h4><p>
<table class="table">
    <tbody>
      <tr>
        <td>アクセス</td>
        <td><%= @picture.access %></td>
      </tr>
      <tr>
        <td>営業時間</td>
        <td><%= @picture.worktime %></td>
      </tr>
      <tr>
        <td>休業日</td>
        <td><%= @picture.rest %></td>
      </tr>
      <tr>
        <td>料金</td>
        <td><%= @picture.fee %></td>
      </tr>
      <tr>
        <td>カード利用</td>
        <td><%= @picture.credit %></td>
      </tr>
       <tr>
        <td>駐車場</td>
        <td><%= @picture.parking %></td>
      </tr>
       <tr>
        <td>駐車台数</td>
        <td><%= @picture.parkingnumber %></td>
      </tr>
       <tr>
        <td>駐車料金</td>
        <td><%= @picture.parkingfee %></td>
      </tr>
       <tr>
        <td>電話番号</td>
        <td><%= @picture.phonenumber %></td>
      </tr>
    </tbody>
    </table>

app/views/pictures/_comment.html.erb
<p>
    <strong>コメンテター:</strong>
    <%= user.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= user.body %>
  </p>

app/views/pictures/_form.html.erb
<%= nested_form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :タイトル %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :説明 %><br>
    <%= f.text_area :content, rows: 5, cols: 50 %>
  </div>

    <div class="field">
    <%= f.label :住所 %><br>
    <%= f.text_field :address %>
  </div>
    <div class="field">
    <%= f.label :アクセス %><br>
    <%= f.text_field :access %>
  </div>
    <div class="field">
    <%= f.label :営業時間 %><br>
    <%= f.text_field :worktime %>
  </div>
   <div class="field">
    <%= f.label :休業日 %><br>
    <%= f.text_field :rest %>
  </div>
   <div class="field">
    <%= f.label :料金 %><br>
    <%= f.text_field :fee %>
  </div>
   <div class="field">
    <%= f.label :カード利用 %><br>
    <%= f.text_field :credit %>
  </div>
   <div class="field">
    <%= f.label :駐車場 %><br>
    <%= f.text_field :parking %>
  </div>
  <div class="field">
    <%= f.label :駐車台数 %><br>
    <%= f.text_field :parkingnumber %>
  </div>
  <div class="field">
    <%= f.label :駐車料金 %><br>
    <%= f.text_field :parkingfee %>
  </div>
  <div class="field">
    <%= f.label :電話番号 %><br>
    <%= f.text_field :phonenumber %>
  </div>
　
　 <div class="field">
    <%= f.label :タイトル %><br>
    <%= f.text_field :title %>
  </div>

  <h4>File Upload</h4>
　<div class="field">
  <%= f.fields_for :assets do |asset_fields| %>
      <p><%= asset_fields.file_field :image %></p>
  </div>
  <% end %>


  <h4>現在の写真</h4>
  
  <%= f.fields_for :assets do |asset_fields| %>

    <% unless asset_fields.object.new_record? %>
      <%= link_to image_tag(asset_fields.object.image.url(:thumb)), 
                  asset_fields.object.image.url(:original) %>
     <div class="field">
     <%= asset_fields.link_to_remove "Remove this" %>
</div>
    <% end %>
  <% end %>

  

  <div class="actions">
    <%= f.submit "そいや"%>
  </div>
<% end %>

app/views/pictures/_good.html.erb
<strong>オススメベスト３</strong><br><br>
<div class="good3">
<% @pictures.each do |picture| %>
<% if picture.assets.present? %>
    <sec>
    <%= image_tag picture.assets.first.image.url, size:"200x150" %><br>
    <a>コメント欄</a></sec>
    <sec>
	<%= image_tag picture.assets.second.image.url, size:"200x150" %><br>
	<a>コメント欄</a></sec>
	<sec>
    <%= image_tag picture.assets.third.image.url, size:"200x150" %><br>
    <a>コメント欄</a></sec>
</div>
<% end %>
<% end %>

app/views/pictures/_map.html.erb
<p><h4>【地図】<h4></p>
<h6>住所：<%= @picture.address %></h6>
<div style='width: 400px;'>
  <div id="map" style='width: 400px; height: 200px;'></div>
<script type='text/javascript'>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});

</script>
</div>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h2>グルメ</h2><h5>〜地元民ならではの情報を満載〜</h5>

<table>
  <tbody class="pict">
    <% @pictures.each do |picture| %>
     <% if picture.assets.present? %>
        <div><hr><blockquote><%= image_tag picture.assets.first.image.url, size:"70x70" %>
         <% end %>
        <%= link_to picture.name,picture %></blockquote><div>
        <%= link_to "Destroy", picture, :confirm => 'Are you sure?', :method => :delete %> 

<%        
=begin
%>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<%
=end
%>
 
    <% end %>
  </tbody>
</table>

<br>

<h6><%= link_to '新規投稿', new_picture_path %><h6>

app/views/pictures/new.html.erb
<h1>新規投稿</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<section class="port">
<p>
  <b class="title"><h3><%= @picture.name %></h3></b><hr>
</p>
<p><%= simple_format @picture.content %></p><hr>

<div class="box0">
<%= render 'good' %>
</div>
<br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br>



<div class="boxA">
<%= render 'address' %>
</div>

<div class="boxB">
<%= render 'map' %>
</div>

<%        
=begin
<div class="boxC">
<p><h4>【写真】<h4></p>
<ul>
    <% @picture.assets.each do |pic| %>
     <a><%= image_tag pic.image.url %></a>
     <%= link_to "Destroy", [@picture, pic], :confirm => 'Are you sure?', :method => :delete %> 
  <% end %>
</ul>
</div>
<%
=end
%>
</section>


<br><br><br>
<%= render "comments/form" %>
  
  
   <!--- Modelのstyleで指定した :midium など渡すことでサイズを指定できる -->

<br><br><br><br><br>
<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to "Destroy", @picture, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back', pictures_path %>